export const data = [
    {
        id: 1,
        clientName: 'João',
        description: 'Mensalidade',
        amount: 150,
        paid: false,
    },
    {
        id: 2,
        clientName: 'Maria',
        description: 'Mensalidade',
        amount: 200,
        paid: false,
    },
    {
        id: 3,
        clientName: 'José',
        description: 'Mensalidade',
        amount: 120,
        paid: false,
    },
    {
        id: 4,
        clientName: 'Ana',
        description: 'Mensalidade',
        amount: 250,
        paid: false,
    },
    {
        id: 5,
        clientName: 'Pedro',
        description: 'Mensalidade',
        amount: 180,
        paid: false,
    },
    {
        id: 6,
        clientName: 'Carla',
        description: 'Mensalidade',
        amount: 110,
        paid: false,
    },
    {
        id: 7,
        clientName: 'Lucas',
        description: 'Mensalidade',
        amount: 300,
        paid: false,
    },
    {
        id: 8,
        clientName: 'Mariana',
        description: 'Mensalidade',
        amount: 140,
        paid: false,
    },
    {
        id: 9,
        clientName: 'Fernanda',
        description: 'Mensalidade',
        amount: 170,
        paid: false,
    },
    {
        id: 10,
        clientName: 'Gustavo',
        description: 'Mensalidade',
        amount: 220,
        paid: false,
    },
    {
        id: 11,
        clientName: 'Rafael',
        description: 'Mensalidade',
        amount: 130,
        paid: false,
    },
    {
        id: 12,
        clientName: 'Renata',
        description: 'Mensalidade',
        amount: 190,
        paid: false,
    },
    {
        id: 13,
        clientName: 'Bianca',
        description: 'Mensalidade',
        amount: 260,
        paid: false,
    },
    {
        id: 14,
        clientName: 'Felipe',
        description: 'Mensalidade',
        amount: 150,
        paid: false,
    },
    {
        id: 15,
        clientName: 'Roberta',
        description: 'Mensalidade',
        amount: 210,
        paid: false,
    },
    {
        id: 16,
        clientName: 'Sergio',
        description: 'Mensalidade',
        amount: 280,
        paid: true,
    },
    {
        id: 17,
        clientName: 'Marina',
        description: 'Mensalidade',
        amount: 230,
        paid: true,
    },
    {
        id: 18,
        clientName: 'Thiago',
        description: 'Mensalidade',
        amount: 170,
        paid: true,
    },
    {
        id: 19,
        clientName: 'Camila',
        description: 'Mensalidade',
        amount: 120,
        paid: true,
    },
    {
        id: 20,
        clientName: 'Isabela',
        description: 'Mensalidade',
        amount: 290,
        paid: true,
    },
    {
        id: 21,
        clientName: 'Paulo',
        description: 'Mensalidade',
        amount: 240,
        paid: true,
    },
    {
        id: 22,
        clientName: 'Luiza',
        description: 'Mensalidade',
        amount: 150,
        paid: true,
    },
    {
        id: 23,
        clientName: 'André',
        description: 'Mensalidade',
        amount: 180,
        paid: true,
    },
    {
        id: 24,
        clientName: 'Mariano',
        description: 'Mensalidade',
        amount: 200,
        paid: true,
    },
    {
        id: 25,
        clientName: 'Cecília',
        description: 'Mensalidade',
        amount: 160,
        paid: true,
    },
    {
        id: 26,
        clientName: 'Gabriel',
        description: 'Mensalidade',
        amount: 250,
        paid: true,
    },
    {
        id: 27,
        clientName: 'Carolina',
        description: 'Mensalidade',
        amount: 130,
        paid: true,
    },
    {
        id: 28,
        clientName: 'Luciana',
        description: 'Mensalidade',
        amount: 170,
        paid: true,
    },
    {
        id: 29,
        clientName: 'Renan',
        description: 'Mensalidade',
        amount: 220,
        paid: true,
    },
    {
        id: 30,
        clientName: 'Viviane',
        description: 'Mensalidade',
        amount: 190,
        paid: true,
    },
];
